version: '3.4'
services:
  sip-calculate-ab:
    build:
      context : .
      dockerfile: Flask.Dockerfile
    image: 148078527676.dkr.ecr.ap-southeast-1.amazonaws.com/sip-calculate-ab:3.0.0
    container_name: sip-calculate-ab
    environment:
     - BACKEND_DEVICELOG_PROD=http://192.168.1.36:3000/api/v3/DeviceLogs/queryGeneral
     - BACKEND_DEVICELOG_PREPROD=http://192.168.1.36:3000/api/v3/DeviceLogs/queryGeneral
     - BACKEND_DEVICELOG_DEV=http://192.168.1.36:3000/api/v3/DeviceLogs/queryGeneral
    ports:
      - 8080:5000