version: '3.4'
services:
  sip-calculate-ab:
    build:
      context : .
      dockerfile: Flask.Dockerfile
    image:  flask:0.0.1
    container_name: sip-calculate-ab
    environment:
     - BACKEND_DEVICELOG_PROD=https://amazone/DeviceLogs/queryGeneral
     - BACKEND_DEVICELOG_PREPROD=https://zalo/DeviceLogs/queryGeneral
     - BACKEND_DEVICELOG_DEV=http://192.168.1.36:3000/api/v3/DeviceLogs/queryGeneral
    ports:
      - 8080:5000