version: '3.4'
services:

  flask:
    build:
      context : ./
      dockerfile: Flask.Dockerfile
    image: flask:0.0.1
    container_name: sip_flask
    volumes:
      - ./:/app
    environment:
     - BACKEND_DEVICELOG=http://192.168.1.36:3000/api/v3/DeviceLogs/queryGeneral
    ports:
      - 8080:5000